spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql.host}
    username: ${mysql.username}
    password: ${mysql.password}
  main:
    banner-mode: off
  redis:
    database: 0
    timeout: 500
    host: ${redis.host}
    port: ${redis.port}
    pool:
      max-active: 8
    password: ${redis.password}
  mail:
    host: smtp.163.com
    username: ${mail.username}
    password: ${mail.password}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
          ssl:
            enable: true

server:
  port: 8060

mybatis-plus:
  global-config:
    banner: false
  configuration:
    call-setters-on-nulls: true