spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://152.136.154.181:3306/todolist
    username: teashirt
    password: 123456
  main:
    banner-mode: off
  redis:
    database: 0
    timeout: 500
    host: 152.136.154.181
    port: 6379
    pool:
      max-active: 8

server:
  port: 8060

mybatis-plus:
  global-config:
    banner: false
  configuration:
    call-setters-on-nulls: true