spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
  main:
    banner-mode: off
  redis:
    database: 0
    timeout: 500
    host: 127.0.0.1
    port: 5378
    pool:
      max-active: 8
    password: Hey-ya
  mail:
    host: smtp.163.com
    username:
    password:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
          ssl:
            enable: true

server:
  port: 8060

mybatis-plus:
  global-config:
    banner: false
  configuration:
    call-setters-on-nulls: true