CREATE TABLE `todolist` (
`id` int NOT NULL AUTO_INCREMENT,
`userid` INT NOT NULL ,
`content` varchar(1000) NOT NULL,
`create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
`update_time` TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
`status` INT DEFAULT 0,
PRIMARY KEY (`id`)
) ENGINE = InnoDB;